### ISSUE TITLE
Modified the play Speed

### ISSUE THREAD

**Issue by skylin008** [MarcelMG/STM32F103C8T6#1]
Your Project is very impressivly.Thank you shared it. 
I had read your blog file,  and did it that store audio file in Nor Flash. 
Nor Flash burn the c code can be via Ymodem protocol, it is very stablel.
I  had a issue as follow:How to Modified the speech play Speed via sample and Pwm.Thank you!

**Comment by MarcelMG** [comment]
Thank you!
If you dive into the code you will see that timer1 triggers the sampling, i.e. in each call of TIM1_UP_IRQHandler() a new value is read from the SPI memory and set as PWM duty-cycle value. So the frequency of the timer1 interrupt determines the playback frequency. You have to change the following:
> 	// so the timer overflow will occur with a frequency of 72MHz/1633=approx. 44.1kHz
	TIM1->ARR = 1633;

44.1kHz is the standard frequency used in most audio recordings. If you want to change playback speed, modify the value 1663.
